apiVersion: v1 
kind: Pod 
metadata: 
  name: worker-app-pod
  labels: 
    name: worker-app-pod
    app: demo-voting-app 
spec: 
  containers: 
  - image: worker-app
    name: kodekloud/examplevotingapp_worker:v1