apiVersion: apps/v1
kind: Deployment
metadata:
  name:  worker-app-deploy
  labels:
    name: worker-app-deploy
    app:  demo-voting-app
spec:
  selector:
    matchLabels:
      name: worker-app-pod
      app:  demo-voting-app
  replicas: 1
  template:
    metadata: 
      name: worker-app-pod
      labels: 
        name: worker-app-pod
        app: demo-voting-app 
    spec: 
      containers: 
      - image: worker-app
        name: kodekloud/examplevotingapp_worker:v1